spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://127.20.0.3:8071
  config:
    import: "optional:configserver:"

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 5