spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8071
    loadbalancer:
      ribbon:
        enable: false
  config:
    import: "optional:configserver:"